Support updating the database
smartshark/prSHARK pull request #1
Opened 2023-08-13 14:23 UTC by myousfi96

In this PR we have the following changes:

1. Fix duplicate entries in the Label field when updating the database.
2. Support tracking for what we need to update using the Timeline API from Github.
3. Break the extended function "parse_pr_list" into smaller pieces.

2023-08-14 05:58 UTC, atrautsch commented on smartshark_plugin.py
> -    pr_system.last_updated = datetime.datetime.now()
good catch!

2023-08-14 06:01 UTC, atrautsch commented on prSHARK/backends/github.py
> -                self._log.error("Problem with getting data via url %s. Code: %s, Error: %s", url, resp.status_code, resp.text)
having only resp.text on a newline does not look more readable to me

2023-08-14 06:01 UTC, atrautsch commented on prSHARK/backends/github.py
> +                                if e['resource'] == 'PullRequest' and e['field'] == 'diff' and e[
should maybe split on the and instead of the dict lookup

2023-08-14 06:01 UTC, atrautsch commented on prSHARK/backends/github.py
> +                    self._log.error("Problem with getting data via url %s. Code: %s, Error: %s", url, resp.status_code,
having only resp.text on a newline does not look more readable to me

2023-08-14 06:02 UTC, atrautsch commented on prSHARK/backends/github.py
> +        url = '{}?state=all'.format(
could be all in one line

2023-08-14 06:05 UTC, atrautsch requested changes
Good changes overall, I have some nits for the style changes.
There are tests and fixtures for this repository. Did the tests run after refactoring?
If yes, you should also extend the existing tests and fixtures with the timeline changes.

2023-08-19 20:04 UTC, myousfi96 commented
Thank you for the review. I've included a test for the timeline and tested it. Regarding the style changes, you're correct, I didn't intend to make them. It's just a habit of mine to accidentally press a shortcut that reformats the entire file

2023-08-23 10:47 UTC, atrautsch approved these changes

2023-08-23 10:47 UTC, merged